name: ess563
channels:
  - conda-forge
dependencies:
  - python=3.9
  - jupyterhub-singleuser=1.3
  - jupyterlab=3.0
  - matplotlib
  - numpy
  - pandas
  - scipy
  - pip
  - obspy
  - pip:
    - tsfel
